// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwkNMmIDstul2cYNqXS3uQGxQ7yGZPEFI',
    appId: '1:416364664156:web:83976844bca562815e1d99',
    messagingSenderId: '416364664156',
    projectId: 'medical-sample-8ee1b',
    authDomain: 'medical-sample-8ee1b.firebaseapp.com',
    storageBucket: 'medical-sample-8ee1b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPogfBNtQLHSRoYGOvvbSP7gfxsSr_THk',
    appId: '1:416364664156:android:72033149e61e1e345e1d99',
    messagingSenderId: '416364664156',
    projectId: 'medical-sample-8ee1b',
    storageBucket: 'medical-sample-8ee1b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUQl5lODVtnbR-FtKbAuQIqzy9En6RYsA',
    appId: '1:416364664156:ios:92014320dab54d8e5e1d99',
    messagingSenderId: '416364664156',
    projectId: 'medical-sample-8ee1b',
    storageBucket: 'medical-sample-8ee1b.firebasestorage.app',
    iosBundleId: 'com.example.medicalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUQl5lODVtnbR-FtKbAuQIqzy9En6RYsA',
    appId: '1:416364664156:ios:92014320dab54d8e5e1d99',
    messagingSenderId: '416364664156',
    projectId: 'medical-sample-8ee1b',
    storageBucket: 'medical-sample-8ee1b.firebasestorage.app',
    iosBundleId: 'com.example.medicalProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwkNMmIDstul2cYNqXS3uQGxQ7yGZPEFI',
    appId: '1:416364664156:web:593e7dfbfa8a9e755e1d99',
    messagingSenderId: '416364664156',
    projectId: 'medical-sample-8ee1b',
    authDomain: 'medical-sample-8ee1b.firebaseapp.com',
    storageBucket: 'medical-sample-8ee1b.firebasestorage.app',
  );

}